all: clean buildMain buildTest runTest

buildMain: task.c
	gcc -o task task.c -std=c89 -lm

buildTest: task_test.c
	gcc -o task_test -Dtask=_task task.c task_test.c -std=c89 -lm

runTest:
	./task_test

clean:
	rm -rf clabs
	