name: C/C++ CI

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]

jobs:

  build-Lab_1:
  
    runs-on: ubuntu-latest

    steps:

      - name: install valgrind and cpplint
        run: |
          sudo apt install valgrind
          sudo pip install cpplint
      - name: build and test
        run: |
          for d in */ ; do
          cd "$d"
          make MakeFile
          cd ..
          done
