name: C/C++ CI

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]

jobs:

  build-Lab_1-Task:
  
    runs-on: ubuntu-latest

    steps:
       
      - name: clone repo
        uses: actions/checkout@v1

      - name: install valgrind and cpplint
        run: |
          sudo apt install valgrind
          sudo pip install cpplint
      - name: build and test
        run: |
          for d in */*/ ; do
          cd "$d"
          make
          cd ..
          done
