name: C/C++ CI

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2
      - name: install valgrind
      
        run: |
          sudo apt install valgrind
#         sudo pip install cpplint
      - name: compiling and test
        
        run: |
           make -C Lab_1/
