name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@Lab_7
      - name: Test
        run: |
          gcc -ftest-coverage -fprofile-arcs -O0 -o test test.c functions.c
          ./test
          gcov -abcfu functions.c
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          files: ./functions.c.gcov
