name: C/C++ CI

on:
  push:
    branches: [ Lab7 ]
  pull_request:
    branches: [ Lab7 ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Fetch
      uses: actions/checkout@master
    - uses: actions/checkout@v2
    - name: compile and test
      run: | 
        for d in */ ; do
        make -C "$d"
        done
    - name: Upload
      uses: codecov/codecov-action@v1
      with: 
       files: |
         ./functions.c.gcov
