name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build Lab_1:
  
    runs-on: ubuntu-latest

    steps:
    
      - name: clone repo
        uses: actions/checkoutv@1

      - name: install valgrind and cpplint
        run: |
          sudo apt install valgrind
          sudo pip install cpplint
